language: groovy

jdk: openjdk10

install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap
  - export PATH="$PATH:`./pkg-build.sh r_path`"

script:
  - ./gradlew build -x test
  - java -jar build/libs/vdjtools-*.jar RInstall
  - wget https://github.com/mikessh/vdjtools-examples/releases/download/1.1/aging_lite.zip
  - unzip aging_lite.zip
  - chmod +x travis.post.sh
  - bash travis.post.sh